databases:
  - name: eternity-db
    plan: free
    databaseName: eternity
    user: eternity

services:
  - type: web
    name: eternity-recuerdos
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eternity-db
          property: connectionString
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
